name: multialign
channels:
        - conda-forge
        - bioconda
dependencies:
        - snakemake == 8.*
        - snakemake-executor-plugin-slurm
        - snakemake-storage-plugin-fs
        - mamba
